### ISSUE TITLE
R Graph Catalog down?

### ISSUE THREAD

**Issue by scienceisfiction** [jennybc/r-graph-catalog#16]
Hi @jennybc 
The link to launch R Graph Catalog doesn't appear to be working anymore. I believe I remembered you showing this during STAT 545 and I was hoping to show it to a grad module I'm teaching at UBC in September (BIOL 548L) so they can quickly get a glimpse of a whole bunch of different charts + code. Am I just missing something?
Thanks!
Melissa

**Comment by jennybc** [comment]
Someone else noticed this 1 - 2 weeks ago and the sys admin noticed we needed to renew the academic license and I saw the digital paperwork go by. I will check on that again ....

**Comment by jennybc** [comment]
Back up now!

**Comment by MonkmanMH** [comment]
And it's down again...

**Comment by jennybc** [comment]
OK I've pinged the sys admin ....
