### ISSUE TITLE
Online version seems to be dead

### ISSUE THREAD

**Issue by oganm** [jennybc/r-graph-catalog#17]
Following the ubc stats link leads to the error

```
Error in shinyAppDir(x) : 
  No Shiny application exists at the path "/nfs/37zfs1-shiny-server/shiny-server/r-graph-catalog"
Calls: runApp ... as.shiny.appobj -> as.shiny.appobj.character -> shinyAppDir
Execution halted
```

I guess UBC people aren't hosting this anymore?

**Comment by jennybc** [comment]
I've pinged the stat sys admins...

**Comment by jennybc** [comment]
It's back. There was a permissions problem because sys admin forgot that shiny apps were hosted in a specific directory. Fixed now. Thanks for letting me know!

**Comment by oganm** [comment]
Seems to be dead again

**Comment by jennybc** [comment]
This is an ongoing struggle.

**Comment by daattali** [comment]
Perhaps transferring this to shinyapps.io so that it would be a hosted solution and not have to be maintained would be helpful? That is of course if this content is allowed on US servers

**Comment by jennybc** [comment]
Yeah I should definitely do that @daattali
