### ISSUE TITLE
Shiny App server not responding

### ISSUE THREAD

**Issue by alcantarar** [jennybc/r-graph-catalog#18]
From the readme, [http://shiny.stat.ubc.ca/r-graph-catalog/](http://shiny.stat.ubc.ca/r-graph-catalog/) is reporting that the site can't be reached. [isitdownrightnow.com](https://www.isitdownrightnow.com/shiny.stat.ubc.ca.html) confirms that the site is down.

**Comment by jennybc** [comment]
Yeah, it is forever going down because no one in the UBC Stat dept really uses it on an ongoing basis. I need to move it somewhere else.

**Comment by jennybc** [comment]
But I've asked for it to be nudged back to life 🤞

**Comment by daattali** [comment]
@jennybc I'm not sure why that shiny server seems to go down often, would you like me to move this app to a different server or do you want it to keep being hosted by UBC?

(I'm also going to unsubscribe from notifications of this repo :)

**Comment by jennybc** [comment]
@daattali Thanks! I've just asked some internal folks if they can make this problem go away for me, but if that fails, yes, I would be delighted if you flung this up on a reliable server. I'll be back in touch.

**Comment by jennybc** [comment]
It's baaaaaack up.
