### ISSUE TITLE
This site can’t be reached

### ISSUE THREAD

**Issue by earlev4** [jennybc/r-graph-catalog#19]
Hi Jenny. Good day! 

I have been trying to reach the R Graph Catalog website for the past couple of days and I get the following message:

**This site can’t be reached**

Any assistance would be greatly appreciated.

Thanks!

**Comment by jennybc** [comment]
It is FOREVER going down. I should move it.

But let me ping the sysadmins.

**Comment by earlev4** [comment]
Thanks so much, Jenny! The site is back up. I appreciate it.
